apiVersion: v1
kind: PersistentVolume
metadata:
  name: MOUNT_NAME
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: MOUNT_NAME
  nfs:
    path: /boston-convertdata/
    server: 176b7485de-dub27.cn-beijing.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MOUNT_NAME
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_HERE
  labels:
    app: SERVICE_NAME_HERE
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: SERVICE_NAME_HERE
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: SERVICE_NAME_HERE
  labels:
    app: SERVICE_NAME_HERE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME_HERE
  template:
    metadata:
      labels:
        app: SERVICE_NAME_HERE
    spec:
      containers:
      - name: SERVICE_NAME_HERE
        image: SERVER_IMAGE_TAG_HERE
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        args:
        - --elasticsearch.host=http://192.168.177.201:9200,http://192.168.177.227:9200
        - --elasticsearch.indexName=video_data_v2_ENV_NAME_HERE
        - --videoInfo.url=http://boston-pipeline-ENV_NAME_HERE/db
        - --image.playbackUrl=http://video-host.ENV_NAME_HERE.richinfoai.com
        - --image.uploadBaseUrl=http://video-host.ENV_NAME_HERE.richinfoai.com:81/files
        - --image.uploadToken=8e782d5d-adda-4de2-a62f-a8e510cc490a
        - --image.vectorUrl=http://greenland-image2vector-test/image2vector/car
        - --image.vectorCachePath=/var/lib/vector
        - --hadoop.conf.dir=/usr/local/boston-convertdata/hadoop-cdh-conf
        - --task.baseUrl=http://47.95.160.36
        - --hdfs.baseUrl=hdfs://cdh1:8020/
        volumeMounts:
        - name: HIGH_DIMENSION_NAME_HERE
          mountPath: /var/lib/vector
          subPath: vector
        - name: MOUNT_NAME
          mountPath: /usr/local/boston-convertdata
      volumes:
      - name: HIGH_DIMENSION_NAME_HERE
        persistentVolumeClaim:
          claimName: HIGH_DIMENSION_NAME_HERE
      - name: MOUNT_NAME
        persistentVolumeClaim:
          claimName: MOUNT_NAME
